// src/config/companies.js
// Company configurations — branding, placementModules, tracks, and features

export const COMPANIES = [
  {
    id: 'comp-accenture',
    slug: 'accenture',
    name: 'Accenture',
    shortName: 'Accenture',
    tagline: 'Technology & Management Consulting',
    description: 'Prepare for Accenture placement exams, coding assessments, and technical interviews.',
    branding: {
      primaryColor: '#A100FF', // Accenture Purple
      primaryHover: '#7900C2',
      badgeBg: 'rgba(161, 0, 255, 0.1)',
      logoText: 'Accenture',
    },
    features: {
      dsa: true,
      sql: true,
      frontend: true,
      assessments: true,
      studyMaterials: true,
      interview: true,
    },
    tracks: [
      { id: 'acc-cognitive', name: 'Cognitive & Critical Reasoning', slug: 'cognitive', questionsCount: 45 },
      { id: 'acc-technical', name: 'Technical Assessment', slug: 'technical', questionsCount: 60 },
      { id: 'acc-coding', name: 'Coding & Algorithms (DSA + SQL + Web)', slug: 'coding', questionsCount: 50 },
      { id: 'acc-communication', name: 'Communication Assessment', slug: 'communication', questionsCount: 30 },
    ],
    placementModules: [
      {
        id: 'selection-process',
        title: 'Selection Process',
        shortTitle: 'Selection Process',
        path: '/selection-process',
        icon: 'Workflow',
        color: '#A100FF',
        desc: '6-Stage Elimination flow: Shortlisting ➔ Same Day (Tech MCQ + Coding + Games) ➔ Comm ➔ Interview',
        badge: 'Elimination',
      },
      {
        id: 'syllabus',
        title: 'Official Syllabus',
        shortTitle: 'Syllabus',
        path: '/syllabus',
        icon: 'BookOpen',
        color: '#8b5cf6',
        desc: 'Accenture 2027 curriculum: C/C++, OOP, DBMS, OS, Cloud, Cyber, DSA, SQL, Web, Games',
        badge: '2027 Pattern',
      },
      {
        id: 'cognitive',
        title: 'Cognitive Games',
        shortTitle: 'Cognitive Games',
        path: '/cognitive',
        icon: 'Brain',
        color: '#6366f1',
        desc: 'Interactive Accenture games: Quick-Fire Bubble Math, Memory Maze, Switch Challenge',
        badge: 'Round 3',
      },
      {
        id: 'technical-mcq',
        title: 'Technical MCQ',
        shortTitle: 'Technical MCQ',
        path: '/technical-mcq',
        icon: 'CheckSquare',
        color: '#059669',
        desc: 'Pseudocode, MS Office, and Networking & Cloud fundamentals questions',
        badge: 'Round 1',
      },
      {
        id: 'dsa',
        title: 'DSA Practice',
        shortTitle: 'DSA Coding',
        path: '/dsa',
        icon: 'Code2',
        color: '#2563eb',
        desc: 'Arrays, Strings, Two Pointer, Sliding Window, Trees, and DP coding problems',
        badge: 'Round 2',
      },
      {
        id: 'sql',
        title: 'SQL Practice',
        shortTitle: 'SQL Query',
        path: '/sql',
        icon: 'Database',
        color: '#0ea5e9',
        desc: 'SELECT, WHERE, JOIN, GROUP BY, Aggregate functions, and subqueries',
        badge: 'Round 2',
      },
      {
        id: 'frontend',
        title: 'Frontend Web',
        shortTitle: 'Frontend Web',
        path: '/frontend',
        icon: 'Globe',
        color: '#ec4899',
        desc: 'HTML, CSS, JavaScript, DOM Manipulation, and REST API live sandbox',
        badge: 'Round 2',
      },
    ],
  },
  {
    id: 'comp-tcs',
    slug: 'tcs',
    name: 'Tata Consultancy Services',
    shortName: 'TCS',
    tagline: 'TCS NQT & Digital Hiring',
    description: 'Target TCS NQT, Digital, and Prime profiles with tailored practice modules.',
    branding: {
      primaryColor: '#0052CC', // TCS Blue
      primaryHover: '#0747A6',
      badgeBg: 'rgba(0, 82, 204, 0.1)',
      logoText: 'TCS',
    },
    features: {
      dsa: true,
      sql: true,
      frontend: true,
      assessments: true,
      studyMaterials: true,
      interview: true,
    },
    tracks: [
      { id: 'tcs-nqt-aptitude', name: 'NQT Foundation (Numerical & Reasoning)', slug: 'nqt-foundation', questionsCount: 40 },
      { id: 'tcs-nqt-advanced', name: 'Advanced Quantitative & Reasoning', slug: 'nqt-advanced', questionsCount: 35 },
      { id: 'tcs-coding-digital', name: 'Digital / Prime Coding', slug: 'tcs-coding', questionsCount: 30 },
    ],
    placementModules: [
      {
        id: 'selection-process',
        title: 'Selection Process',
        shortTitle: 'Selection Process',
        path: '/selection-process',
        icon: 'Workflow',
        color: '#0052CC',
        desc: 'TCS NQT Ninja, Digital & Prime package bands and recruitment stages',
        badge: 'NQT Flow',
      },
      {
        id: 'syllabus',
        title: 'Official Syllabus',
        shortTitle: 'Syllabus',
        path: '/syllabus',
        icon: 'BookOpen',
        color: '#2563eb',
        desc: 'TCS NQT Foundation, Advanced Section, and Coding section curriculum',
        badge: '2027 Pattern',
      },
      {
        id: 'tcs-nqt-foundation',
        title: 'NQT Foundation Aptitude',
        shortTitle: 'NQT Foundation',
        path: '/assessments?track=nqt-foundation',
        icon: 'CheckSquare',
        color: '#0052CC',
        desc: 'Numerical Ability, Verbal Ability, and Reasoning Ability foundation test',
        badge: 'Part A',
      },
      {
        id: 'tcs-nqt-advanced',
        title: 'Advanced Quant & Logic',
        shortTitle: 'Advanced Quant',
        path: '/assessments?track=nqt-advanced',
        icon: 'Brain',
        color: '#6366f1',
        desc: 'Advanced Quantitative & Reasoning ability for Digital/Prime qualification',
        badge: 'Part B',
      },
      {
        id: 'tcs-coding',
        title: 'Digital & Prime Coding',
        shortTitle: 'Digital Coding',
        path: '/dsa',
        icon: 'Code2',
        color: '#059669',
        desc: 'Hands-on programming questions for Ninja, Digital (7 LPA), and Prime (9 LPA)',
        badge: 'Coding Test',
      },
      {
        id: 'tcs-sql',
        title: 'SQL & Data Querying',
        shortTitle: 'SQL Practice',
        path: '/sql',
        icon: 'Database',
        color: '#0ea5e9',
        desc: 'TCS technical round database queries and SQL problem solving',
        badge: 'Tech Round',
      },
    ],
  },
  {
    id: 'comp-infosys',
    slug: 'infosys',
    name: 'Infosys',
    shortName: 'Infosys',
    tagline: 'InfyTQ & DSE Specialist',
    description: 'Master Infosys Specialist Programmer, DSE, and Systems Engineer assessments.',
    branding: {
      primaryColor: '#007CC3', // Infosys Blue
      primaryHover: '#00629B',
      badgeBg: 'rgba(0, 124, 195, 0.1)',
      logoText: 'Infosys',
    },
    features: {
      dsa: true,
      sql: true,
      frontend: false,
      assessments: true,
      studyMaterials: true,
      interview: true,
    },
    tracks: [
      { id: 'inf-reasoning', name: 'Mathematical & Logical Ability', slug: 'reasoning', questionsCount: 40 },
      { id: 'inf-pseudo', name: 'Pseudocode & Algorithms', slug: 'pseudocode', questionsCount: 35 },
      { id: 'inf-sp-coding', name: 'Specialist Programmer Coding', slug: 'sp-coding', questionsCount: 25 },
    ],
    placementModules: [
      {
        id: 'selection-process',
        title: 'Selection Process',
        shortTitle: 'Selection Process',
        path: '/selection-process',
        icon: 'Workflow',
        color: '#007CC3',
        desc: 'Infosys recruitment flow: Online Test (Reasoning + Pseudo + Verbal) ➔ Tech & HR Interview',
        badge: 'Infy Process',
      },
      {
        id: 'syllabus',
        title: 'Official Syllabus',
        shortTitle: 'Syllabus',
        path: '/syllabus',
        icon: 'BookOpen',
        color: '#0284c7',
        desc: 'Reasoning Ability, Technical Ability, Pseudocode, and SP Coding curriculum',
        badge: '2027 Pattern',
      },
      {
        id: 'inf-reasoning',
        title: 'Reasoning & Aptitude',
        shortTitle: 'Reasoning Test',
        path: '/assessments?track=reasoning',
        icon: 'Brain',
        color: '#007CC3',
        desc: 'Mathematical critical thinking, logical deduction, and verbal comprehension',
        badge: 'Section 1',
      },
      {
        id: 'inf-pseudocode',
        title: 'Pseudocode & Logic',
        shortTitle: 'Pseudocode',
        path: '/technical-mcq',
        icon: 'CheckSquare',
        color: '#059669',
        desc: 'Code tracing, dry-running loops, recursive calls, and time complexity',
        badge: 'Section 2',
      },
      {
        id: 'inf-coding',
        title: 'Specialist Coding (SP / DSE)',
        shortTitle: 'SP / DSE Coding',
        path: '/dsa',
        icon: 'Code2',
        color: '#8b5cf6',
        desc: 'Advanced algorithmic challenges for 9.5 LPA Specialist Programmer roles',
        badge: '9.5 LPA Role',
      },
      {
        id: 'inf-sql',
        title: 'DBMS & SQL Practice',
        shortTitle: 'SQL Practice',
        path: '/sql',
        icon: 'Database',
        color: '#0ea5e9',
        desc: 'Relational design, normalization questions, and complex SQL joins',
        badge: 'Technical',
      },
    ],
  },
  {
    id: 'comp-wipro',
    slug: 'wipro',
    name: 'Wipro',
    shortName: 'Wipro',
    tagline: 'Elite National Talent Hunt',
    description: 'Ace Wipro Elite NLTH and Turbo hiring assessments.',
    branding: {
      primaryColor: '#107C41', // Wipro Green
      primaryHover: '#0E6B38',
      badgeBg: 'rgba(16, 124, 65, 0.1)',
      logoText: 'Wipro',
    },
    features: {
      dsa: true,
      sql: true,
      frontend: false,
      assessments: true,
      studyMaterials: true,
      interview: true,
    },
    tracks: [
      { id: 'wip-aptitude', name: 'Quantitative & Logical Aptitude', slug: 'aptitude', questionsCount: 40 },
      { id: 'wip-coding', name: 'Hands-on Coding Assessment', slug: 'coding', questionsCount: 20 },
      { id: 'wip-essay', name: 'Written Communication Test', slug: 'written-comm', questionsCount: 15 },
    ],
    placementModules: [
      {
        id: 'selection-process',
        title: 'Selection Process',
        shortTitle: 'Selection Process',
        path: '/selection-process',
        icon: 'Workflow',
        color: '#107C41',
        desc: 'Wipro Elite NLTH & Turbo workflow, sectional cutoff guidelines, and stages',
        badge: 'Elite Flow',
      },
      {
        id: 'syllabus',
        title: 'Official Syllabus',
        shortTitle: 'Syllabus',
        path: '/syllabus',
        icon: 'BookOpen',
        color: '#059669',
        desc: 'Aptitude, Essay Writing, and 2-problem coding assessment syllabus',
        badge: '2027 Pattern',
      },
      {
        id: 'wip-aptitude',
        title: 'Aptitude & Reasoning',
        shortTitle: 'Aptitude Test',
        path: '/assessments?track=aptitude',
        icon: 'CheckSquare',
        color: '#107C41',
        desc: 'Quantitative aptitude, logical deduction, and verbal English ability',
        badge: 'Round 1',
      },
      {
        id: 'wip-coding',
        title: 'Elite NLTH Coding',
        shortTitle: 'Elite Coding',
        path: '/dsa',
        icon: 'Code2',
        color: '#2563eb',
        desc: '2 Coding problems (Easy + Medium array/string manipulation)',
        badge: 'Round 2',
      },
      {
        id: 'wip-essay',
        title: 'Written Communication',
        shortTitle: 'Essay Test',
        path: '/study-materials',
        icon: 'FileText',
        color: '#d97706',
        desc: 'Essay writing test evaluated by automated grammar & vocabulary engine',
        badge: 'Round 3',
      },
      {
        id: 'wip-sql',
        title: 'SQL & Database Queries',
        shortTitle: 'SQL Practice',
        path: '/sql',
        icon: 'Database',
        color: '#0ea5e9',
        desc: 'Core queries and normalization questions for technical interviews',
        badge: 'Tech Round',
      },
    ],
  },
]

export function getCompanyBySlug(slug) {
  if (!slug) return null
  return COMPANIES.find((c) => c.slug.toLowerCase() === slug.toLowerCase()) || null
}
